services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mvcagrocaretech
      POSTGRES_USER: mvcagrocaretech
      POSTGRES_PASSWORD: mvcagrocaretech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: mvcagrocaretech
      RABBITMQ_DEFAULT_PASS: mvcagrocaretech
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: